#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:34.833833.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("add_river_legend() works", {

  f <- kwb.smartwater:::add_river_legend

  expect_error(
    f()
    # Argument "ext_rivers" fehlt (ohne Standardwert)
  )

})
