#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:34.917226.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("n_trees_to_veg_class_increment() works", {

  f <- kwb.smartwater:::n_trees_to_veg_class_increment

  expect_error(
    f()
    # Argument "n_trees" fehlt (ohne Standardwert)
  )

})
