#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:34.833833.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("plot_into_png_generic() works", {

  f <- kwb.smartwater:::plot_into_png_generic

  expect_error(
    f()
    # Argument "filename" fehlt (ohne Standardwert)
  )

})
