#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:34.833833.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("Berlin_and_waterbodies() works", {

  f <- kwb.smartwater:::Berlin_and_waterbodies

  expect_error(
    f()
    # Please set argument 'districPolygons' in call to Berlin_and_waterbodies()
  )

})
