#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2026-07-17 11:42:07.655713.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("character(0)() works", {

  expect_error(
    kwb.smartwater:::character(0)()
    # Objekt 'character' nicht gefunden
  )

})

