#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2026-07-17 11:33:04.201605.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("calculate_water_balance() works", {

  expect_error(
    kwb.smartwater:::calculate_water_balance()
    # Argument "blocks" fehlt (ohne Standardwert)
  )

})

