#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:34.833833.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("classes_to_color() works", {

  f <- kwb.smartwater:::classes_to_color

  expect_error(
    f()
    # Please set argument 'colorVector' in call to classes_to_color()
  )

})
