#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:34.833833.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("interpolate_multipleNA() works", {

  f <- kwb.smartwater:::interpolate_multipleNA

  expect_error(
    f()
    # Argument "data_vector" fehlt (ohne Standardwert)
  )

})
