#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:34.833833.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("read_from_text() works", {

  f <- kwb.smartwater:::read_from_text

  expect_error(
    f()
    # Argument "text_file" fehlt (ohne Standardwert)
  )

})
