#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:34.833833.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("value_to_classes() works", {

  f <- kwb.smartwater:::value_to_classes

  expect_error(
    f()
    # Argument "river_list" fehlt (ohne Standardwert)
  )

})
