#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2026-07-17 11:42:07.655713.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("run_plumber_api() works", {

  kwb.smartwater:::run_plumber_api()

})

