#
# This test file has been generated by kwb.test::create_test_files()
# launched by user fdpunt on 2026-07-31 14:30:20.934085.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_water_quality_indicators() works", {

  kwb.smartwater:::get_water_quality_indicators()

})

