#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:37.561437.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("get_plot_fun_args_for_surface_reduction() works", {

  f <- kwb.smartwater:::get_plot_fun_args_for_surface_reduction

  expect_error(
    f()
    # Argument "type" fehlt (ohne Standardwert)
  )

})
