#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2026-07-17 11:59:37.561437.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("plot_effect_of_disconnect() works", {

  f <- kwb.smartwater::plot_effect_of_disconnect

  expect_error(
    f()
    # Argument "type" fehlt (ohne Standardwert)
  )

})
