#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2026-07-17 11:35:26.13559.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("rabimo_block_to_partial_areas_m2() works", {

  expect_error(
    kwb.smartwater:::rabimo_block_to_partial_areas_m2()
    # Argument "block" fehlt (ohne Standardwert)
  )

})

